name: Deploy staging

on:
  push:
    branches:
      - main
concurrency:
  group: deploy-staging
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t actai/procurement-web:staging .
      - name: Save image
        run: docker save actai/procurement-web:staging | gzip > procurement-web-image.tar.gz
      - name: Upload image and configs to server
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -azvP
          path: procurement-web-image.tar.gz compose.yml
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_path: ${{ secrets.SSH_APP_DIR }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Update staging container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            #!/usr/bin/env bash
            set -e
            cd ${{ secrets.SSH_APP_DIR }}
            docker load --input procurement-web-image.tar.gz
            docker compose up -d web-staging
            docker image prune --force --filter "until=72h"
